server:
  address: 0.0.0.0
  port: 8083

spring:
  application:
    name: client-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug

services:
  text-counting-service:
    url: http://localhost:8084
  token-sorting-service:
    url: http://localhost:8085